---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - name: gitlab-ui
      port: 80
      protocol: TCP
    - name: gitlab-ssh
      port: 22
      protocol: TCP
  selector:
    app: gitlab
    tier: frontend