---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  type: NodePort
  ports:
    - name: gitlab-ui
      port: 80
      protocol: TCP
#      targetPort: 30080
#      nodePort: 30080
    - name: gitlab-ssh
      port: 22
      protocol: TCP
#      targetPort: 22
#      nodePort: 30022
  selector:
    app: gitlab
    tier: frontend


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
    tier: frontend
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: frontend
    spec:
      containers:
        - image: gitlab/gitlab-ee:latest #9.1.0-ce.0
          name: gitlab
          env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: |
              postgresql['enable'] = false
              gitlab_rails['db_encoding'] = 'utf8'
              redis['enable'] = false
              gitlab_rails['db_username'] = ENV['GITLAB_DATABASE_USERNAME'];
              gitlab_rails['db_password'] = ENV['GITLAB_DATABASE_PASSWORD'];
              gitlab_rails['db_host'] = ENV['POSTGRES_DB_HOST'];
              gitlab_rails['db_port'] = ENV['POSTGRES_PORT'];
              gitlab_rails['db_database'] = ENV['POSTGRES_DB_NAME'];
              gitlab_rails['redis_host'] = ENV['REDIS_HOST'];
              gitlab_rails['redis_port'] = ENV['REDIS_PORT'];
          - name: GITLAB_DATABASE_DATABASE
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: DB_NAME
          - name: GITLAB_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: DB_USER
          - name: GITLAB_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: DB_PASS
          - name: GITLAB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: GITLAB_ROOT_PASSWORD
          - name: GITLAB_SECRETS_DB_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: GITLAB_SECRETS_DB_KEY_BASE
          - name: GITLAB_SECRETS_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: GITLAB_SECRETS_SECRET_KEY_BASE
          - name: GITLAB_SECRETS_OTP_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: GITLAB_SECRETS_OTP_KEY_BASE

          envFrom:
             - configMapRef:
                 name: redis-configmap
             - configMapRef:
                 name: gitlab-configmap
             - configMapRef:
                 name: postgres-config
          ports:
            - containerPort: 80
              name: gitlab
          volumeMounts:
            - name: gitlab
              mountPath: /var/opt/gitlab
              subPath: gitlab_data
            - name: gitlab
              mountPath: /etc/gitlab
              subPath: gitlab_configuration
          livenessProbe:
            httpGet:
              path: /users/sign_in
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /users/sign_in
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
      volumes:
        - name: gitlab
          emptyDir: {}
#          persistentVolumeClaim:
#            claimName: gitlab-claim
