name: User Input Workflow

on:
  workflow_dispatch:
    inputs:
      myVariable:
        description: 'Enter a value'
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use User Input
        run: echo "User input value is ${{ github.event.inputs.myVariable }}"
